apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: ob-be-dotnet
  name: ob-be-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ob-be-dotnet
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: ob-be-dotnet
      name: ob-be-dotnet
    spec:
      containers:
        - name: ob-be-dotnet
          image: acronboarding.azurecr.io/OB-BE-dotnet:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: sql-server-claudia
                  key: on-boarding-astra-star-claudia
            - name: AuthorizationServer__Address
              valueFrom:
                configMapKeyRef:
                  name: config-claudia
                  key: AuthorizationServerAddress
          ports:
          - containerPort: 80
          resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 125m
                memory: 256Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ob-be-dotnet
  name: ob-be-dotnet
spec:
  ports:
  - port: 80
  type: LoadBalancer
  selector:
    app: ob-be-dotnet
status:
  loadBalancer: {}
